version: '3.8'

services:
  web:
    build: ./todobackend
    command: /opt/app/todo/start-server.sh
    volumes:
      - ./todobackend/:/usr/src/todobackend/
    ports:
      - 8020:8020
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: